name: p2000
channels:
  - conda-forge
  - udst
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - boost-cpp=1.70.0=h6a4c333_2
  - bzip2=1.0.8=hfa6e2cd_2
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37hb32ad35_0
  - cfitsio=3.470=hfa6e2cd_2
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - colorama=0.4.3=py_0
  - contextily=1.0rc2=py_0
  - cryptography=2.8=py37hb32ad35_1
  - curl=7.65.3=h4496350_0
  - cycler=0.10.0=py_2
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=he025d50_1004
  - fiona=1.8.13=py37hb7fdc2d_0
  - freetype=2.10.0=h563cfd7_1
  - freexl=1.0.5=hd288d7e_1002
  - gdal=3.0.2=py37hdf43c64_0
  - geographiclib=1.50=py_0
  - geopandas=0.6.2=py_0
  - geopy=1.20.0=py_0
  - geos=3.8.0=he025d50_0
  - geotiff=1.5.1=h765a46f_7
  - gettext=0.19.8.1=hb01d8f6_1002
  - glib=2.58.3=py37hc0c2ac7_1002
  - hdf4=4.2.13=hf8e6fe8_1003
  - hdf5=1.10.4=nompi_hcc15c50_1106
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py37_1000
  - importlib_metadata=1.4.0=py37_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython=7.11.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.2=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=hfa6e2cd_1001
  - json5=0.8.5=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=1.2.4=py_0
  - jupyterlab_server=1.0.6=py_0
  - kealib=1.4.10=heacb130_1003
  - kiwisolver=1.1.0=py37he980bc4_0
  - krb5=1.16.4=hdd46e55_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.1=default_hf44288c_0
  - libcurl=7.65.3=h4496350_0
  - libffi=3.2.1=h6538335_1006
  - libgdal=3.0.2=h1155b67_0
  - libiconv=1.15=hfa6e2cd_1005
  - libkml=1.3.0=h4ece8bf_1010
  - liblapack=3.8.0=14_mkl
  - libnetcdf=4.6.2=h396784b_1001
  - libpng=1.6.37=h7602738_0
  - libpq=11.5=hb0bdaea_2
  - libsodium=1.0.17=h2fa13f4_0
  - libspatialindex=1.9.3=he025d50_1
  - libspatialite=4.3.0a=he9c6e69_1033
  - libssh2=1.8.2=h642c060_2
  - libtiff=4.1.0=h56a325e_0
  - libxml2=2.9.10=h9ce36c8_0
  - lz4-c=1.8.3=he025d50_1001
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - markupsafe=1.1.1=py37hfa6e2cd_0
  - matplotlib=3.1.2=py37_1
  - matplotlib-base=3.1.2=py37h2981e6d_1
  - mercantile=1.1.2=py_0
  - mistune=0.8.4=py37hfa6e2cd_1000
  - mkl=2019.4=245
  - more-itertools=8.0.2=py_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.3=py_0
  - notebook=6.0.1=py37_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h57dd2e7_3
  - openssl=1.1.1d=hfa6e2cd_0
  - pandas=0.25.3=py37he350917_0
  - pandoc=2.9.1.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.2=py_0
  - pcre=8.43=h6538335_0
  - pickleshare=0.7.5=py37_1000
  - pillow=7.0.0=py37h9ea1dd6_0
  - pip=19.3.1=py37_0
  - poppler=0.67.0=h1707e21_8
  - poppler-data=0.4.9=1
  - postgresql=11.5=h06f7779_2
  - proj=6.2.1=ha7a8c7b_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - pycparser=2.19=py37_1
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyproj=2.4.2.post1=py37h9716dcf_0
  - pyqt=5.9.2=py37h6538335_4
  - pyrsistent=0.15.6=py37hfa6e2cd_0
  - pysocks=1.7.1=py37_0
  - python=3.7.3=h510b542_1
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pywin32=225=py37hfa6e2cd_0
  - pywinpty=0.5.7=py37_0
  - pyzmq=18.1.1=py37h16f9016_0
  - qt=5.9.7=hc6833c9_1
  - rasterio=1.1.2=py37h2617b1b_0
  - requests=2.22.0=py37_1
  - rtree=0.9.3=py37hbf79ddb_0
  - send2trash=1.5.0=py_0
  - setuptools=44.0.0=py37_0
  - shapely=1.6.4=py37h2130f3d_1007
  - sip=4.19.8=py37h6538335_0
  - six=1.13.0=py37_0
  - snuggs=1.4.7=py_0
  - sqlite=3.30.1=hfa6e2cd_0
  - tbb=2018.0.5=he980bc4_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tiledb=1.6.3=h7b000aa_0
  - tk=8.6.10=hfa6e2cd_0
  - tornado=6.0.3=py37hfa6e2cd_0
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.7=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_1003
  - winpty=0.4.3=4
  - xerces-c=3.2.2=h6538335_1004
  - xz=5.2.4=h2fa13f4_1001
  - zeromq=4.3.2=h6538335_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.3.7=h508b16e_0
  - pip:
    - ipywidgets==7.5.1
    - keplergl==0.1.2
    - numpy==1.18.1
    - traittypes==0.2.1
    - widgetsnbextension==3.5.1
prefix: C:\Users\Mikhail\Anaconda3\envs\p2000

